In [1]:
%matplotlib inline


[Learn the Basics](intro.html) ||
[Quickstart](quickstart_tutorial.html) ||
**Tensors** ||
[Datasets & DataLoaders](data_tutorial.html) ||
[Transforms](transforms_tutorial.html) ||
[Build Model](buildmodel_tutorial.html) ||
[Autograd](autogradqs_tutorial.html) ||
[Optimization](optimization_tutorial.html) ||
[Save & Load Model](saveloadrun_tutorial.html)

# Tensors

Tensors are a specialized data structure that are very similar to arrays and matrices.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to [NumPy’s](https://numpy.org/) ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and
NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see `bridge-to-np-label`). Tensors
are also optimized for automatic differentiation (we'll see more about that later in the [Autograd](autogradqs_tutorial.html)_
section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!


In [2]:
import torch
import numpy as np

## Initializing a Tensor/初始化Tensor

Tensors can be initialized in various ways. Take a look at the following examples:

**Directly from data**

Tensors can be created directly from data. The data type is automatically inferred.



In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**From a NumPy array**

Tensors can be created from NumPy arrays (and vice versa - see `bridge-to-np-label`).



In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**From another tensor:**

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.



In [5]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1096, 0.7822],
        [0.8554, 0.8117]]) 



**With random or constant values:**

``shape`` is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.



In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5936, 0.1355, 0.3229],
        [0.3180, 0.3878, 0.4472]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


--------------




## Tensor的属性

Tensor attributes describe their shape, datatype, and the device on which they are stored.



In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------




## 对Tensor的可能操作

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing,
indexing, slicing), sampling and more are
comprehensively described [here](https://pytorch.org/docs/stable/torch.html)_.

Each of these operations can be run on the GPU (at typically higher speeds than on a
CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

**By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using**
``.to`` method (after checking for GPU availability). Keep in mind that copying large tensors
across devices can be expensive in terms of time and memory!



In [8]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

Try out some of the operations from the list.
If you're familiar with the NumPy API, you'll find the Tensor API a breeze to use.




### **Standard numpy-like indexing and slicing:**



In [13]:
tensor = torch.rand(4, 4)
print(tensor)
print("\n")
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")

tensor([[0.5332, 0.6748, 0.6438, 0.9831],
        [0.3078, 0.4966, 0.0850, 0.7926],
        [0.3682, 0.4115, 0.5289, 0.5639],
        [0.0529, 0.1692, 0.8310, 0.8551]])


First row: tensor([0.5332, 0.6748, 0.6438, 0.9831])
First column: tensor([0.5332, 0.3078, 0.3682, 0.0529])
Last column: tensor([0.9831, 0.7926, 0.5639, 0.8551])


修改

In [14]:
tensor[:,1] = 0
print(tensor)

tensor([[0.5332, 0.0000, 0.6438, 0.9831],
        [0.3078, 0.0000, 0.0850, 0.7926],
        [0.3682, 0.0000, 0.5289, 0.5639],
        [0.0529, 0.0000, 0.8310, 0.8551]])


**Joining tensors** 

You can use ``torch.cat`` to concatenate a sequence of tensors along a given dimension.
See also [torch.stack](https://pytorch.org/docs/stable/generated/torch.stack.html)_,
another tensor joining option that is subtly different from ``torch.cat``.



In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.5332, 0.0000, 0.6438, 0.9831, 0.5332, 0.0000, 0.6438, 0.9831, 0.5332,
         0.0000, 0.6438, 0.9831],
        [0.3078, 0.0000, 0.0850, 0.7926, 0.3078, 0.0000, 0.0850, 0.7926, 0.3078,
         0.0000, 0.0850, 0.7926],
        [0.3682, 0.0000, 0.5289, 0.5639, 0.3682, 0.0000, 0.5289, 0.5639, 0.3682,
         0.0000, 0.5289, 0.5639],
        [0.0529, 0.0000, 0.8310, 0.8551, 0.0529, 0.0000, 0.8310, 0.8551, 0.0529,
         0.0000, 0.8310, 0.8551]])


### **Arithmetic operations**

**矩阵乘法/ Matrix Multiplication**

In [17]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
# ``tensor.T`` returns the transpose of a tensor
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[1.6651, 0.9980, 1.0911, 1.4038],
        [0.9980, 0.7301, 0.6052, 0.7647],
        [1.0911, 0.6052, 0.7333, 0.9412],
        [1.4038, 0.7647, 0.9412, 1.4245]])

这些代码都是在计算一个张量 tensor 与它的转置矩阵的乘积，也就是矩阵的平方。

1. y1 = tensor @ tensor.T：这是 Python 中的运算符重载，表示使用 @ 运算符计算矩阵乘积。这行代码将 tensor 与它的转置矩阵相乘，并将结果赋值给变量 y1。

2. y2 = tensor.matmul(tensor.T)：这是 PyTorch 中的矩阵乘积函数，它的作用和 @ 运算符相同。这行代码将 tensor 与它的转置矩阵相乘，并将结果赋值给变量 y2。

3. y3 = torch.rand_like(y1)：这一行创建一个形状与 y1 相同的新张量 y3，并将其初始化为随机值。

4. torch.matmul(tensor, tensor.T, out=y3)：这是 PyTorch 中的矩阵乘积函数，它的作用和 matmul 方法相同。这行代码将 tensor 与它的转置矩阵相乘，并将结果写入 y3 中。由于指定了 out 参数，所以不会创建新的张量。

**元素乘法/element-wise product**

In [19]:
# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[0.2843, 0.0000, 0.4144, 0.9664],
        [0.0948, 0.0000, 0.0072, 0.6281],
        [0.1356, 0.0000, 0.2798, 0.3179],
        [0.0028, 0.0000, 0.6905, 0.7312]])

**Single-element tensors** 

If you have a one-element tensor, for example by aggregating all
values of a tensor into one value, you can convert it to a Python
numerical value using ``item()``:



In [20]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

6.545401573181152 <class 'float'>


### 原位置操作/In-place operations

Operations that store the result into the operand are called in-place. 

They are denoted by a ``_`` suffix.
For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.



In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

<div class="alert alert-info"><h4>Note</h4><p>In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss
     of history. Hence, their use is discouraged.</p></div>



--------------





## Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory
locations, and changing one will change	the other.



### Tensor to NumPy array



In [25]:
t = torch.ones(5)
print(f"tensor_version: {t}")
n = t.numpy()
print(f"numpy_version: {n}")

tensor_version: tensor([1., 1., 1., 1., 1.])
numpy_version: [1. 1. 1. 1. 1.]


**A change in the tensor reflects in the NumPy array.**



In [26]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


### NumPy array to Tensor



In [27]:
n = np.ones(5)
t = torch.from_numpy(n)

**Changes in the NumPy array reflects in the tensor.**



In [24]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
